name: CD Pipeline

on:

  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/HNG_2/fastapi-book-project
          git fetch origin main
          git merge origin main
          source ~/HNG_2/HNG_venv/bin/bin/activate
          sudo apt install python3-pip -y
          pip install -r requirements.txt -y
          sudo systemctl restart fastapi
          sudo systemctl restart nginx
